### ISSUE TITLE
DRC Issues (Unable to Pass DRC)

### ISSUE THREAD

**Issue by DevinJM3** [actions-for-kicad/kicad-actions#17]
When running a DRC report in the KiCad GUI I have 0 violations, although when running this with GitHub actions it is saying there is 1 DRC violation. I am unsure if the KiCad -actions is using a older version of the CLI or maybe a windows to Linux issue. Any insight or help would be awesome!

![Image](https://github.com/user-attachments/assets/1a4e94f9-3c2e-47f4-befd-0eb70c9bfe85)

![Image](https://github.com/user-attachments/assets/56fe4883-c1a3-4ba7-af5c-53fb3d08ae41)

**Comment by DevinJM3** [comment]
Here is a link to the repo that is having issues: https://github.com/DevinJM3/Lipo-Charger-Board

**Comment by Nick-v-L** [comment]
Hi @DevinJM3,

Can you provide the following information:
- What is the exact version of KiCad that you use? (About KiCad -> Copy version info)
- Can you export the erc.rpt and also post this here?

An issue I had myself a few days ago is that I used KiCad 9.0.0 locally and the action uses the latest KiCad 9.0 version (so 9.0.1).

**Comment by Nick-v-L** [comment]
Update:
I saw that KiCad 9.0.2 just released two days ago so this is automatically used in the repo. A thing that I can add is that I build this repo also for every patch version of KiCad. So then you can use it like this:

```yaml
- name: KiCad 9
  uses: actions-for-kicad/kicad-actions@v1.3-k9 # Uses the latest KiCad 9.x.x version (currently 9.0.2)

- name: KiCad 9.0
  uses: actions-for-kicad/kicad-actions@v1.3-k9.0 # Uses the latest KiCad 9.0.x version (currently 9.0.2)

- name: KiCad 9.0.2
  uses: actions-for-kicad/kicad-actions@v1.3-k9.0.2 # Precisely use KiCad 9.0.2
```
